linux:
  script:
    - git clone https://github.com/openturns/openturns.git
    - pushd openturns
    - cmake -DCMAKE_INSTALL_PREFIX=$PWD/install -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_C_COMPILER=/usr/bin/clang -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so -DUSE_SPHINX=OFF -DUSE_COTIRE=ON -DCOTIRE_TESTS=OFF -DCOTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES="-j8" .
    - make python_unity -j8
    - make install/fast
    - popd
    - cmake -DCMAKE_INSTALL_PREFIX=$PWD/install -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_C_COMPILER=/usr/bin/clang -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so -DCMAKE_CXX_FLAGS="-Wall -Wshadow" -DOpenTURNS_DIR=$PWD/openturns/install/lib/cmake/openturns -DUSE_SALOME=OFF .
    - make install -j8
    - make tests -j8
    - ctest --output-on-failure --timeout 100
  except:
    - master

mingw:
  script:
    - git clone https://github.com/openturns/openturns.git
    - pushd openturns/distro/windows
    - tar xzf /usr/share/openturns-developers-windeps-1.8.tar.gz
    - pushd openturns-developers-windeps
    - rm -r mingw-w64-x86_64
    - tar xzf /usr/share/mingw-w64-x86_64.tar.gz
    - popd
    - make ot-install JOBS=4
    - popd
    - pushd distro/windows
    - make OT_PREFIX=$PWD/../../openturns/build-i686-w64-mingw32/install JOBS=4
  except:
    - master

mingw-tag:
  script:
    - git clone https://github.com/openturns/openturns.git
    - pushd openturns/distro/windows
    - tar xzf /usr/share/openturns-developers-windeps-1.8.tar.gz
    - pushd openturns-developers-windeps
    - rm -r mingw-w64-x86_64
    - tar xzf /usr/share/mingw-w64-x86_64.tar.gz
    - popd
    - make ot-module-installer JOBS=4
    - popd
    - pushd distro/windows
    - make OT_PREFIX=$PWD/../../openturns/build-i686-w64-mingw32/install JOBS=4 CHECK_OT=n
  artifacts:
    paths:
    - openturns/distro/windows/openturns*.exe
    - distro/windows/otgui*.exe
  only:
    - tags
