linux:
  script:
    - docker build docker/linux -t linux
    - docker run --rm --volume `pwd`:/tmp/otgui linux sh -c "/tmp/otgui/docker/linux/run_docker_build.sh"
  except:
    - tags

mingw:
  script:
    - docker build docker/mingw -t mingw
    - docker run --rm --volume `pwd`:/tmp/otgui mingw sh -c "/tmp/otgui/docker/mingw/run_docker_build.sh"
  except:
    - tags

linux-tag:
  script:
    - docker build docker/linux -t linux
    - docker run --rm --volume `pwd`:/tmp/otgui linux sh -c "/tmp/otgui/docker/linux/run_docker_build.sh `id -u` `id -g`"
  artifacts:
    paths:
      - otgui*.AppImage
  only:
    - tags

mingw-tag:
  script:
    - docker build docker/mingw -t mingw
    - docker run --rm --volume `pwd`:/tmp/otgui mingw sh -c "/tmp/otgui/docker/mingw/run_docker_build.sh `id -u` `id -g`"
  artifacts:
    paths:
      - otgui*.exe
  only:
    - tags
