linux:
  script:
    - docker build docker/linux -t linux
    - docker run --rm --volume `pwd`:/io linux sh -c "/io/docker/linux/run_docker_build.sh"
  except:
    - tags

mingw:
  script:
    - docker build docker/mingw -t mingw
    - docker run --rm --volume `pwd`:/io mingw sh -c "/io/docker/mingw/run_docker_build.sh"
  except:
    - tags

linux-tag:
  script:
    - docker build docker/linux -t linux
    - docker run --rm --volume `pwd`:/io linux sh -c "/io/docker/linux/run_docker_build.sh `id -u` `id -g`"
  artifacts:
    paths:
      - persalys*.AppImage
  only:
    - tags

mingw-tag:
  script:
    - docker build docker/mingw -t mingw
    - docker run --rm --volume `pwd`:/io mingw sh -c "/io/docker/mingw/run_docker_build.sh `id -u` `id -g`"
  artifacts:
    paths:
      - persalys*.exe
  only:
    - tags
